url_shortener/models.py
import string
from datetime import datetime
from random import choices
from url_shortener.extensions import db


class Url(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_code = db.Column(db.String(7), unique=True)
    visits = db.Column(db.Integer, default=0)
    created_date = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_code = self.generate_short_code()

    def generate_short_code(self):
        characters = string.digits + string.ascii_letters
        short_code = ''.join(choices(characters, k=7))

        url = self.query.filter_by(short_code=short_code).first()  # TODO: optimize with exist

        if url:
            return self.generate_short_code()

        return short_code

url_shortener/__init__.py
from flask import Flask
from redis import Redis
import rq


def create_app(config_file='settings.py'):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)

    # Init extensions
    from url_shortener.extensions import db
    db.init_app(app)

    app.redis = Redis.from_url(app.config['REDIS_URL'])
    app.rq_queue = rq.Queue(app.config['REDIS_QUEUE'], connection=app.redis)

    # Blueprints
    from url_shortener.main import bp as main_bp
    app.register_blueprint(main_bp)

    from url_shortener.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    return app

url_shortener/auth.py
# -*- coding: utf-8 -*-
"""
    authentication.basic
    ~~~~~~~~~~~~~~~~~~~~
    HTTP Basic Auth
    http://flask.pocoo.org/snippets/8/
"""

from functools import wraps
from flask import request, Response, current_app


def check_auth(username, password):
    """This function is called to check if a username /
    password combination is valid.
    """
    return username == current_app.config['ADMIN_USERNAME'] and password == current_app.config['ADMIN_PASSWORD']


def authenticate():
    """Sends a 401 response that enables basic auth"""
    return Response(
    'Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})


def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

url_shortener/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from url_shortener.main import routes

url_shortener/main/routes.py
from flask import render_template, request, redirect, url_for, current_app, jsonify
from url_shortener.extensions import db
from url_shortener.models import Url
from url_shortener.auth import requires_auth
from url_shortener.utils import shorten_url
from url_shortener.main import bp


@bp.route('/<short_code>')
def redirect_to_url(short_code):
    url = Url.query.filter_by(short_code=short_code).first_or_404()
    url.visits += 1
    db.session.commit()

    return redirect(url.original_url, code=303)


@bp.route('/')
@requires_auth
def index():
    return render_template('index.html', title='New Document')


@bp.route('/add_url', methods=['POST'])
@requires_auth
def add_url():
    original_url = request.form['original_url']
    url = shorten_url(original_url)

    if url:
        return render_template('url_added.html', title='Add', original_url=url.original_url, short_code=url.short_code)
    else:
        # TODO: flash message
        return redirect(url_for('main.index'))


@bp.route('/stats')
@bp.route('/stats/<int:page>')
@requires_auth
def stats(page=1):
    # urls = Url.query.order_by(Url.visits.desc()).all()
    urls = Url.query.order_by(Url.visits.desc()).paginate(page, 10, False)

    return render_template('stats.html', title='Stats', urls=urls)  # TODO: pass title names, datatable integration


@bp.route('/api/start-job/single', methods=['POST'])
def start_job_batch_short_url_sms_single():
    body = request.get_json()

    job = current_app.rq_queue.enqueue('url_shortener.tasks.batch_short_url_sms_single', body, job_timeout=1000)

    response_object = {
        "status": "success",
        "data": {
            "job_id": job.get_id()
        }
    }

    return jsonify(response_object), 202


@bp.route('/api/start-job/multi', methods=['POST'])
def start_job_batch_short_url_sms_multi():
    body = request.get_json()

    job = current_app.rq_queue.enqueue('url_shortener.tasks.batch_short_url_sms_multi', body, job_timeout=1000)

    response_object = {
        "status": "success",
        "data": {
            "job_id": job.get_id()
        }
    }

    return jsonify(response_object), 202


@bp.route('/api/get-job/<job_id>', methods=['GET'])
def get_job_status(job_id):
    job = current_app.rq_queue.fetch_job(job_id)

    if job:
        response_object = {
            "status": "success",
            "data": {
                "job_id": job.get_id(),
                "job_enqueued_at": job.enqueued_at,
                "job_started_at": job.started_at,
                "job_ended_at": job.ended_at,
                "job_status": job.get_status(),
                "job_exception": job.exc_info,
                "job_result": job.result,
                "job_progress": job.meta.get('progress', 0)
            },
        }
    else:
        response_object = {"status": "error"}
    return jsonify(response_object)

url_shortener/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <h3>Add Short URL</h3>

    <form class="uk-form-horizontal uk-margin" method="POST" action="{{ url_for('main.add_url') }}">
        <div class="uk-margin">
            <input class="uk-input uk-width-5-6" type="text" name="original_url" placeholder="Original URL">
            <button class="uk-button uk-button-primary" type="submit">Shortenen</button>
        </div>
    </form>
{% endblock content %}

url_shortener/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/js/uikit-icons.min.js"></script>

    {% if title %}
        <title>URL Shortener - {{ title }}</title>
    {% else %}
        <title>URL Shortener</title>
    {% endif %}

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <div class="uk-container uk-height-viewport uk-position-relative">
        <div class="uk-section">
            <div class="uk-container">
                {% block content %} {% endblock %}
            </div>
        </div>
        <footer class="uk-section-xsmall uk-position-bottom uk-position-absolute">
            <div class="uk-container uk-position-center">
                <p>Made by <a class="uk-link-text" href="#" target="_blank">&#129514; CadenaLabs </a>&#8226; 2020</p>
            </div>
        </footer>
    </div>
</body>
</html>

url_shortener/templates/stats.html
{% extends "layout.html" %}
{% block content %}
    <h3>URL Stats</h3>

    <table class="uk-table uk-table-divider uk-table-hover">
        <thead>
            <tr>
                <th class="uk-width-xlarge">Original URL</th>
                <th>Short Code</th>
                <th>Visits Count</th>
            </tr>
        </thead>
        <tbody>
            {% for url in urls.items %}
            <tr>
                <td><img src="https://www.google.com/s2/favicons?domain={{ url.original_url }}" alt="favicon"/><a href="{{ url.original_url }}">{{ url.original_url }}</a></td>
                <td><a href="{{ url_for('main.redirect_to_url', short_code=url.short_code, _external=True) }}">{{ url.short_code }}</a></td>
                <td>{{ url.visits }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <ul class="uk-pagination">
        <li><a href="{{ url_for('main.stats', page=urls.prev_num)}}"><span class="uk-margin-small-right" uk-pagination-previous></span> Previous</a></li>
        <li class="uk-margin-auto-left"><a href="{{ url_for('main.stats', page=urls.next_num) }}">Next <span class="uk-margin-small-left" uk-pagination-next></span></a></li>
    </ul>
{% endblock content %}

url_shortener/templates/url_added.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.4/dist/js/uikit-icons.min.js"></script>

    <title>Url Added</title>
</head>
<body>
    <div class="uk-section">
        <div class="uk-container">

            <h3>Short URL</h3>

            <div class="uk-card uk-card-default uk-card-body uk-width-1-2@m">
                <h3 class="uk-card-title">{{ original_url }}</h3>
                <p>Short Code: <a href="{{ url_for('main.redirect_to_url', short_code=short_code, _external=True) }}">{{ short_code }}</a></p>
            </div>

        </div>
    </div>
</body>
</html>